<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AvaloniaIncludeApplicationIconAsWindowIcon>false</AvaloniaIncludeApplicationIconAsWindowIcon>

  </PropertyGroup>
  <ItemGroup>
    <None Remove="StartupWindow.xaml" />
  </ItemGroup>
  <ItemGroup>
    <AvaloniaResource Include="Icons\spotify_green_logo_full.png" />
    <AvaloniaResource Include="Icons/file_icon.png" />
    <AvaloniaResource Include="Icons/spotify_icon_black.png" />
    <AvaloniaResource Include="Icons/spot_white_logo_full.png" />


  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia.Controls.ColorPicker" Version="11.3.2" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.2" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.2" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.2" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Include="Avalonia.Diagnostics" Version="11.3.2">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="DotNetEnv" Version="3.1.1" />
    <PackageReference Include="ManagedBass" Version="4.0.2" />
    <PackageReference Include="ManagedBass.Fx" Version="4.0.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.8" />
    <PackageReference Include="RangeSlider.Avalonia" Version="2.1.0" />
    <PackageReference Include="SpotifyAPI.Web" Version="7.2.1" />
    <PackageReference Include="SpotifyAPI.Web.Auth" Version="7.2.1" />
    <PackageReference Include="System.IO.Ports" Version="9.0.9" />
  </ItemGroup>

    

  <ItemGroup>
    <Folder Include="Local Music\" />
    <Folder Include="Native\win-x64\" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Frontend Logic\LumikitWindow.axaml.cs">
      <DependentUpon>LumikitWindow.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="UI\Windows\LumikitWindow.axaml.cs">
      <DependentUpon>LumikitWindow.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="UI\Windows\NewTrackPopup.axaml.cs">
      <DependentUpon>NewTrackPopup.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="UI\Windows\ProviderPickerWindow.axaml.cs">
      <DependentUpon>ProviderPickerWindow.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="UI\Controls\TimelineView.axaml.cs">
      <DependentUpon>TimelineView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <AvaloniaXaml Include="UI\Windows\StartupWindow.xaml">
      <Generator>MSBuild:Compile</Generator>
    </AvaloniaXaml>
  </ItemGroup>
</Project>
